name: 'Capture Output'
author: 'selfagency'
description: 'Capture the output (and duration) of a command as a GitHub Actions `output` or file'
branding:
  icon: 'list'
  color: 'green'
inputs:
  cmd:
    description: 'Bash command to run'
    type: string
    required: true
  args:
    description: 'Comma separated list of arguments to pass to the command'
    type: string
    required: false
  hide-warnings:
    description: 'Hide warnings in error output'
    type: boolean
    required: false
    default: false
  file:
    description: 'Full path to save file'
    type: string
    required: false
  fail:
    description: Fail if the command returns a non-zero exit code
    type: boolean
    required: false
    default: true
outputs:
  output:
    description: 'Output of the command'
  stdout:
    description: 'Command `stdout` output'
  stderr:
    description: 'Command `stderr` output'
  error-code:
    description: 'Command exit code'
  duration:
    description: 'Duration of the command in seconds'
runs:
  using: 'node20'
  main: 'dist/action.js'
